version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  profile-svc-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - profile-svc-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  profile-svc:
    build:
      context: .
      dockerfile: profile-svc/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - profile-svc-db
      - kafka

  store-of-value-svc-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - store-of-value-svc-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  store-of-value-svc:
    build:
      context: .
      dockerfile: store-of-value-svc/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - store-of-value-svc-db
      - kafka

  payment-svc-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - payment-svc-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  payment-svc:
    build:
      context: .
      dockerfile: payment-svc/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - payment-svc-db
      - kafka

  events-svc-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - events-svc-pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  events-svc:
    build:
      context: .
      dockerfile: events-svc/Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - events-svc-db
      - kafka

volumes:
  profile-svc-pgdata:
  store-of-value-svc-pgdata:
  payment-svc-pgdata:
  events-svc-pgdata:
