spring:
    application:
        name: events_svc
    kafka:
        bootstrap-servers: localhost:9092
    webflux:
        base-path: /api/events
server:
    port: 8084


logging:
    pattern:
        level: "%5p"
        console: "%d{yyyy-MM-dd HH:mm:ss} | %clr(%5p) | %X{traceId} | %m%n"
    level:
        root: INFO

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /v3/api-docs
    packages-to-scan: com.smugi.store_of_value_svc
    paths-to-match: /auth/**