spring:
  r2dbc:
    url: r2dbc:postgresql://events-svc-db:5432/events_svcdb
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8084

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.smugi.store_of_value_svc
  paths-to-match: /auth/**